/**
 * Phase 7.7 — collaborative whiteboard contract.
 *
 * The whiteboard is a flat list of `WhiteboardOp` items. Each op is
 * self-contained: peers apply ops in the order they arrive (last-write-wins).
 * Conflicting strokes are accepted — the canvas is intentionally additive.
 *
 * Two transport paths:
 *   - Realtime: gateway emits/receives `whiteboard:op` for individual ops
 *     and `whiteboard:clear` for a full reset.
 *   - Late-join replay: client requests the snapshot once on JOIN; server
 *     emits `whiteboard:snapshot` with the persisted Op array.
 *
 * The op shape stays narrow (no JS classes, no nested polymorphism) so it
 * can be safely JSON-encoded and persisted as Postgres `jsonb`.
 */

export interface WhiteboardPoint {
  x: number;
  y: number;
}

export type WhiteboardTool = 'pen' | 'eraser' | 'text' | 'line' | 'rect' | 'circle';

/** One stroke / shape / text label. */
export interface WhiteboardOp {
  /** UUID generated by the originating client. Idempotent re-broadcasts use the same id. */
  id: string;
  tool: WhiteboardTool;
  /** CSS color string (#rrggbb or rgba(...)). */
  color: string;
  /** Line / outline width in CSS pixels. */
  size: number;
  /** Pen / eraser strokes use `points`; shapes use the first two as start/end. */
  points: WhiteboardPoint[];
  /** Only for tool === 'text'. Caller is responsible for keeping it short. */
  text?: string;
  /** Author for debugging / future per-author features (not enforced server-side). */
  authorId: string;
  /** ISO timestamp; tie-breaker if ops collide on the same id. */
  createdAt: string;
}

/** Realtime payloads. */
export interface WhiteboardOpPayload {
  op: WhiteboardOp;
}

export interface WhiteboardClearPayload {
  /** participantId that pressed clear; informational only. */
  byParticipantId: string;
  at: string;
}

/** Snapshot delivered to late joiners. */
export interface WhiteboardSnapshotPayload {
  revision: number;
  ops: WhiteboardOp[];
}
